# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=25)),
                ('image', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
